baseurl = "/"
languageCode = "en-US"
title = "John Henry Cruz's Portfolio"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "flex_copy.png"
  author = "John Henry Cruz"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "kid-codei"
  Email         = "jhec.819@gmail.com"
  Twitter       = "hoyits_john"
  LinkedIn      = "johnhenrycruz"
  Stackoverflow = "users/11761433/kid-codei?tab=profile"
  Instagram     = "johnhenrycruz/"
#  Medium        = "username"
#  Telegram      = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "https://johnhenrycruz.netlify.com/MyResume.pdf"
